// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKBg44vflhWjSYw9XEXirjnW1ypCISE6M',
    appId: '1:940257093309:web:84a1f7662c14bdbf7639d4',
    messagingSenderId: '940257093309',
    projectId: 'chat-app-6d2c6',
    authDomain: 'chat-app-6d2c6.firebaseapp.com',
    storageBucket: 'chat-app-6d2c6.appspot.com',
    measurementId: 'G-8R7Y92X4YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWB1LZBpkpinHE4-MM91B6jhLD4MZ9mdY',
    appId: '1:940257093309:android:60b95b61e1908f2c7639d4',
    messagingSenderId: '940257093309',
    projectId: 'chat-app-6d2c6',
    storageBucket: 'chat-app-6d2c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_HI-7vka9XeKJ5LTvhPigOJbmlSQSkx4',
    appId: '1:940257093309:ios:02a3e10602d93a187639d4',
    messagingSenderId: '940257093309',
    projectId: 'chat-app-6d2c6',
    storageBucket: 'chat-app-6d2c6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_HI-7vka9XeKJ5LTvhPigOJbmlSQSkx4',
    appId: '1:940257093309:ios:02a3e10602d93a187639d4',
    messagingSenderId: '940257093309',
    projectId: 'chat-app-6d2c6',
    storageBucket: 'chat-app-6d2c6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKBg44vflhWjSYw9XEXirjnW1ypCISE6M',
    appId: '1:940257093309:web:727e0397a9eb647f7639d4',
    messagingSenderId: '940257093309',
    projectId: 'chat-app-6d2c6',
    authDomain: 'chat-app-6d2c6.firebaseapp.com',
    storageBucket: 'chat-app-6d2c6.appspot.com',
    measurementId: 'G-EX1HJ9QRGB',
  );
}
